FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY backend/package*.json ./
COPY database ./prisma

RUN npm install --legacy-peer-deps --no-audit --no-fund
RUN npx prisma generate --schema=./prisma/schema.prisma

EXPOSE 8000
