FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps --no-audit --no-fund
RUN npx prisma generate

EXPOSE 8000
